name: MetaGPA
channels:
  - bioconda
  - conda-forge
dependencies:
  - SPAdes=4.0.0
  - cd-hit=4.8.1
  - hmmer=3.3.2
  - bowtie2=2.4.1
  - samtools=1.11
  - bedtools=2.30.0
  - perl=5.32.1
  - perl-bioperl
  - bwa=0.7.18
  - perl-math-cdf=0.1
  - quast=5.3.0
  - perl-statistics-descriptive
  - seqtk=1.4